mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: 123456
  log_level: dev

logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true

system:
  host: "0.0.0.0"
  port: 8080
  env: release

upload:
  size: 2
  path: uploads/file

site_info:
  create_at: "2024-03-12"
  bei_an: lef10-7
  title: zhou
  qq_image: x.png
  version: 0.0.1
  email: 1665434994@qq.com
  wechat_image: y.png
  name: zhou
  job: cs
  addr: zhangzhou
  slogan: zhou
  slogan_en: zhouEN
  web: https://www.time1043.com/
  bilibili_url: https://space.bilibili.com/259090980
  gitee_url: https://gitee.com/plktime1043
  github_url: https://github.com/Time1043


email:
  host: smtp.qq.com
  port: 465
  user: xxx@qq.com
  password: xxx
  default_from_email: time1043
  use_ssl: true
  user_tls: true
qi_niu:
  enable: false
  access_key: UMM-xx-FdRIf-xx
  secret_key: xx
  bucket: time1043
  cdn: xx://xx.xx.com/
  zone: xx
  size: 5
jwt:
  secret: xxx
  expires: 48
  issuer: xx
qq:
  app_id: "xx"
  key: xx
  redirect: https://xx.xx.com/login?flag=qq
